<?php
/**
 * Template for single wc_docs posts
 *
 * @package WooCommerce_Docs_JA
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();
?>

<div class="wc-docs-wrapper">
	<div class="wc-docs-container">
		
		<!-- Left Sidebar: Category Navigation -->
		<aside class="wc-docs-sidebar wc-docs-sidebar-left">
			<div class="wc-docs-sidebar-inner">
				<h3 class="wc-docs-sidebar-title"><?php esc_html_e( 'Documentation', 'woocommerce-docs-ja' ); ?></h3>
				<?php
				$categories = get_terms(
					array(
						'taxonomy'   => 'wc_docs_category',
						'hide_empty' => false,
						'parent'     => 0,
					)
				);

				if ( ! empty( $categories ) && ! is_wp_error( $categories ) ) {
					echo '<nav class="wc-docs-category-nav">';
					wc_docs_render_category_tree( $categories, get_the_ID() );
					echo '</nav>';
				}
				?>
			</div>
		</aside>

		<!-- Main Content -->
		<main class="wc-docs-main-content">
			<?php
			while ( have_posts() ) :
				the_post();
				?>
				<article id="post-<?php the_ID(); ?>" <?php post_class( 'wc-docs-article' ); ?>>
					
					<header class="wc-docs-header">
						<h1 class="wc-docs-title"><?php the_title(); ?></h1>
						
						<?php
						$categories = get_the_terms( get_the_ID(), 'wc_docs_category' );
						if ( $categories && ! is_wp_error( $categories ) ) :
							?>
							<div class="wc-docs-breadcrumb">
								<?php
								$breadcrumbs = array();
								foreach ( $categories as $category ) {
									$breadcrumbs[] = sprintf(
										'<a href="%s">%s</a>',
										esc_url( get_term_link( $category ) ),
										esc_html( $category->name )
									);
								}
								echo implode( ' / ', $breadcrumbs );
								?>
							</div>
						<?php endif; ?>
						
						<?php
						$last_updated = get_post_meta( get_the_ID(), 'last_updated', true );
						if ( $last_updated ) :
							?>
							<div class="wc-docs-meta">
								<span class="wc-docs-updated">
									<?php
									printf(
										/* translators: %s: Last updated date */
										esc_html__( 'Last updated: %s', 'woocommerce-docs-ja' ),
										esc_html( date_i18n( get_option( 'date_format' ), strtotime( $last_updated ) ) )
									);
									?>
								</span>
							</div>
						<?php endif; ?>
					</header>

					<div class="wc-docs-content">
						<?php the_content(); ?>
					</div>

					<footer class="wc-docs-footer">
						<?php
						// Previous/Next navigation
						$prev_post = get_previous_post();
						$next_post = get_next_post();

						if ( $prev_post || $next_post ) :
							?>
							<nav class="wc-docs-pagination">
								<?php if ( $prev_post ) : ?>
									<div class="wc-docs-prev">
										<span class="wc-docs-nav-label"><?php esc_html_e( 'Previous', 'woocommerce-docs-ja' ); ?></span>
										<a href="<?php echo esc_url( get_permalink( $prev_post->ID ) ); ?>">
											<?php echo esc_html( get_the_title( $prev_post->ID ) ); ?>
										</a>
									</div>
								<?php endif; ?>
								
								<?php if ( $next_post ) : ?>
									<div class="wc-docs-next">
										<span class="wc-docs-nav-label"><?php esc_html_e( 'Next', 'woocommerce-docs-ja' ); ?></span>
										<a href="<?php echo esc_url( get_permalink( $next_post->ID ) ); ?>">
											<?php echo esc_html( get_the_title( $next_post->ID ) ); ?>
										</a>
									</div>
								<?php endif; ?>
							</nav>
						<?php endif; ?>
					</footer>

				</article>
			<?php endwhile; ?>
		</main>

		<!-- Right Sidebar: Table of Contents -->
		<aside class="wc-docs-sidebar wc-docs-sidebar-right">
			<div class="wc-docs-sidebar-inner wc-docs-toc-wrapper">
				<h3 class="wc-docs-sidebar-title"><?php esc_html_e( 'On this page', 'woocommerce-docs-ja' ); ?></h3>
				<nav class="wc-docs-toc" id="wc-docs-toc">
					<!-- TOC will be generated by JavaScript -->
				</nav>
			</div>
		</aside>

	</div>
</div>

<?php
get_footer();

/**
 * Render category tree recursively.
 *
 * @param array $categories Categories to render.
 * @param int   $current_post_id Current post ID.
 * @param int   $level Depth level.
 */
function wc_docs_render_category_tree( $categories, $current_post_id, $level = 0 ) {
	if ( empty( $categories ) ) {
		return;
	}

	echo '<ul class="wc-docs-category-list wc-docs-category-level-' . esc_attr( $level ) . '">';

	foreach ( $categories as $category ) {
		$child_categories = get_terms(
			array(
				'taxonomy'   => 'wc_docs_category',
				'hide_empty' => false,
				'parent'     => $category->term_id,
			)
		);

		$has_children        = ! empty( $child_categories ) && ! is_wp_error( $child_categories );
		$is_current_category = has_term( $category->term_id, 'wc_docs_category', $current_post_id );

		$class_names = array( 'wc-docs-category-item' );
		if ( $has_children ) {
			$class_names[] = 'has-children';
		}
		if ( $is_current_category ) {
			$class_names[] = 'current-category';
		}

		echo '<li class="' . esc_attr( implode( ' ', $class_names ) ) . '">';

		if ( $has_children ) {
			echo '<button class="wc-docs-category-toggle" aria-expanded="' . ( $is_current_category ? 'true' : 'false' ) . '">';
			echo '<span class="wc-docs-category-icon"></span>';
			echo '</button>';
		}

		printf(
			'<a href="%s" class="wc-docs-category-link%s">%s <span class="wc-docs-category-count">(%d)</span></a>',
			esc_url( get_term_link( $category ) ),
			$is_current_category ? ' current' : '',
			esc_html( $category->name ),
			$category->count
		);

		// Get posts in this category
		$posts = get_posts(
			array(
				'post_type'      => 'wc_docs',
				'posts_per_page' => -1,
				'tax_query'      => array(
					array(
						'taxonomy' => 'wc_docs_category',
						'field'    => 'term_id',
						'terms'    => $category->term_id,
					),
				),
				'orderby'        => 'title',
				'order'          => 'ASC',
			)
		);

		if ( ! empty( $posts ) ) {
			echo '<ul class="wc-docs-post-list">';
			foreach ( $posts as $post ) {
				$is_current = ( $post->ID === $current_post_id );
				printf(
					'<li class="wc-docs-post-item%s"><a href="%s">%s</a></li>',
					$is_current ? ' current-post' : '',
					esc_url( get_permalink( $post->ID ) ),
					esc_html( $post->post_title )
				);
			}
			echo '</ul>';
		}

		if ( $has_children ) {
			wc_docs_render_category_tree( $child_categories, $current_post_id, $level + 1 );
		}

		echo '</li>';
	}

	echo '</ul>';
}
